### ISSUE TITLE
BUG profile

### ISSUE THREAD

**Issue by SirSiegmeyer** [fkropfhamer/ivent-platform#44]
![image](https://user-images.githubusercontent.com/102315699/226173626-aa1e4db4-475e-497a-9bd0-98c275c8c20d.png)
![image](https://user-images.githubusercontent.com/102315699/226173660-fa527567-9d4a-49b6-84ed-fc59a0d5bd92.png)

**Comment by fkropfhamer** [comment]
can't reproduce :)
